### ISSUE TITLE
Allow to define .clabot at organisation level

### ISSUE THREAD

**Issue by maoo** [finos/cla-bot#10]
I am evaluating the cla-bot to validate Pull Requests across different projects that are hosted in our [github org](github.com/symphonyoss); for this reason, I need to be able to define a `.clabot` configuration at organisation level and avoid the project to overrule it.

The solution can be composed by 2 blocks:
- If cla-bot fails resolving the project's `.clabot` file, it will fallback into `https://github.com/<user/org_name>/clabot-config/.clabot`
- A configuration flag (ie `forceOrgConfig`) that forces `.clabot` to be resolved at organisation level

I am submitting a PR that I've [tested against a test repo](https://github.com/ssf-admin/clabot-test/pull/3#issuecomment-303710830); configuration is stored in [ssf-admin/clabot-config](https://github.com/ssf-admin/clabot-config).

Please note; the PR is not ready for merge; documentation and testing is missing; feedback is welcome, especially considering my entry-level node skills.

**Comment by ColinEberhardt** [comment]
Further to the comments here: https://github.com/ColinEberhardt/cla-bot/pull/11#issuecomment-303729114

>  I need to be able to define a .clabot configuration at organisation level and avoid the project to overrule it.

Can you ever really achieve that?

> A configuration flag (ie forceOrgConfig) that forces .clabot to be resolved at organisation level

Someone could then turn it off at a project level?

**Comment by maoo** [comment]
Moving the conversation on https://github.com/ColinEberhardt/cla-bot/pull/11 and closing this issue
