### ISSUE TITLE
Cannot deploy using serverless, getting AccessDenied on S3

### ISSUE THREAD

**Issue by maoo** [finos/cla-bot#101]
I'm trying to deploy cla-bot using serverless, following docs on [DEPLOY.md](https://github.com/ColinEberhardt/cla-bot/blob/develop/DEPLOY.md)

Deployment runs smooth:
```
$ serverless deploy --stage staging

Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (11.5 MB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
................
Serverless: Stack update finished...
Service Information
service: cla-bot
stage: staging
region: us-east-1
stack: cla-bot-staging
api keys:
  None
endpoints:
  POST - https://********.execute-api.us-east-1.amazonaws.com/staging/cla-check
functions:
  cla-bot: cla-bot-staging-cla-bot
```

However, when I take the POST endpoint, copy into the GitHub App Endpoint URL and comment an issue, I get an AccessDenied error on CloudWatch:

```
2018-10-12T14:17:10.542Z	81f88a00-ce29-11e8-9c4d-a9fcf2832d13	(node:1) UnhandledPromiseRejectionWarning: AccessDenied: Access Denied
at Request.extractError (/var/task/cla-bot/node_modules/aws-sdk/lib/services/s3.js:580:35)
at Request.callListeners (/var/task/cla-bot/node_modules/aws-sdk/lib/sequential_executor.js:109:20)
at Request.emit (/var/task/cla-bot/node_modules/aws-sdk/lib/sequential_executor.js:81:10)
at Request.emit (/var/task/cla-bot/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/var/task/cla-bot/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/task/cla-bot/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/task/cla-bot/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/task/cla-bot/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/task/cla-bot/node_modules/aws-sdk/lib/request.js:685:12)
at Request.callListeners (/var/task/cla-bot/node_modules/aws-sdk/lib/sequential_executor.js:119:18)
```

I checked AWS resources and everything seems to be in place; the only strange thing seems to be the API Gateway configuration, which doesn't seem to have an Execution Role set; I tried to copy the ARN from the role created by the serverless deployment, but doesn't allow me to paste and save.

![screen shot 2018-10-12 at 16 29 53](https://user-images.githubusercontent.com/327285/46875570-4ec9ae80-ce3c-11e8-94db-2b7d3e126178.png)

Any idea what is going on? Any help is appreciated, thanks.

**Comment by ColinEberhardt** [comment]
Hi @maoo - the access denied exception stacktrace isn't complete, but I am guessing it relates to the code here:

https://github.com/ColinEberhardt/cla-bot/blob/develop/cla-bot/logger.js#L37

In a recent release I moved from logging to DynamoDB to writing logs to S3. This is more efficient (viewing logs doesn't execute a Dynamo query), and costs less money :-)

The execution role for the lambda function should have 'put' permissions on S3:

https://github.com/ColinEberhardt/cla-bot/blob/develop/serverless.yml#L7

Note - the execution role isn't part of the API Gateway integration, it is on the Lambda function itself. Here is my lambda execution role:

![image](https://user-images.githubusercontent.com/1098110/47112802-4c59c100-d24f-11e8-8d4f-f568d43f3f4b.png)

If I look-up this role within IAM, I can see the following policy:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "logs:CreateLogStream"
            ],
            "Resource": [
                "arn:aws:logs:us-east-1:462989979267:log-group:/aws/lambda/cla-bot-prod-cla-bot:*"
            ],
            "Effect": "Allow"
        },
        {
            "Action": [
                "logs:PutLogEvents"
            ],
            "Resource": [
                "arn:aws:logs:us-east-1:462989979267:log-group:/aws/lambda/cla-bot-prod-cla-bot:*:*"
            ],
            "Effect": "Allow"
        },
        {
            "Action": [
                "s3:PutObject",
                "s3:PutObjectAcl"
            ],
            "Resource": "arn:aws:s3:::cla-bot/*",
            "Effect": "Allow"
        }
    ]
}
```

As you can see, it gives read / write permissions on CloudWatch and the required 'put' actions for S3.

**Comment by ColinEberhardt** [comment]
Hi @maoo - it looks like your lambda has permissions to write to a bucket names `cla-bot`:

~~~
arn:aws:s3:::cla-bot/*
~~~

But you bucket is called `cla-bot-staging`

![image](https://user-images.githubusercontent.com/1098110/49332856-8c30f980-f5ac-11e8-9c98-b648f049a21a.png)

**Comment by ColinEberhardt** [comment]
> could you please confirm that the s3 bucket must be manually created?

Yes ... apologies, I haven't added that to the serverless config.

**Comment by maoo** [comment]
Found the issue! And fixed it! :-)

There is a `"cla-bot"` string hardcoded in [`logger.js`](https://github.com/ColinEberhardt/cla-bot/blob/develop/src/logger.js#L45).

[PR submitted](https://github.com/ColinEberhardt/cla-bot/pull/108)
