### ISSUE TITLE
eslint behaves differently on Travis and locally

### ISSUE THREAD

**Issue by maoo** [finos/cla-bot#164]
When running `npm run lint` on Travis CI, I get different results thant running it locally.

Before digging this up further, I'd like to know if...
- am I the only one having this issue? Or is anyone else able to reproduce this issue? This is the last Travis build on `develop` branch - https://travis-ci.org/finos/cla-bot/builds/610261606
- could it be the different node version used by Travis CI (version 8, quite old) ?

**Comment by ColinEberhardt** [comment]
I’ve not experienced that before - but I’d anticipate it is a versioning issue, either with node itself or npm / yarn, are you using the same package manager locally? is these a lock file? etc ...

**Comment by maoo** [comment]
Thanks for the hint @ColinEberhardt .

Using nvm, I've installed the same node and npm version used in https://travis-ci.org/finos/cla-bot/builds/610261606 , but I still get different linting errors. I'll work around it by only pushing for the linting fixes reported in Travis CI.

Apart from the difficulties during the development phase, this issue is blocking me to test and merge https://github.com/finos/cla-bot/pull/161 ; any help to figure out the linting issue on https://travis-ci.org/finos/cla-bot/builds/610481159 would be super helpful.

**Comment by mcleo-d** [comment]
@maoo - Let's find some time to debug on your local machine so we can reinstate project linting on the CI. We'll check your node versions and will also make sure your code editor is providing inline feedback.

**Comment by maoo** [comment]
Issue was fixed by https://github.com/finos/cla-bot/pull/187
