### ISSUE TITLE
Can we add support for GitLab?

### ISSUE THREAD

**Issue by ColinEberhardt** [finos/cla-bot#182]
As per request here: https://github.com/finos/open-developer-platform/issues/15

Explore the possibility of adding GitLab support (or forking the project to add support)

Technical Requirements:
- [ ] Works on GitLab Ultimate and gitlab.com
- [ ] Identities are whitelisted via GitHub IDs and email address domains (as the current cla-bot)
- [ ] Validate Merge Requests in GitLab, as the current CLA bot validates Pull Requests

**Comment by maoo** [comment]
@ColinEberhardt - I'm going to close this issue, given that we implemented https://github.com/ScottLogic/gitlab-cla-bot . Maybe we could also link the project from README.md ?
