### ISSUE TITLE
Adding a bot to the list of contributors

### ISSUE THREAD

**Issue by sclassen** [finos/cla-bot#196]
We recently added the hosted cla-bot version to our projects.
We also receive dependency update pull requests form dependabot.

So far I failed to add dependabot to the list of users which signed the CLA.
Of course the bot did not actually sign the CLA but its contributions are acceptable for our organization even without a signed CLA.

I tried the following user names:
* dependabot
* @dependabot[bot]
* @dependabot

If i look into the logs of cla-bot i see the following line:
```
The contributors @dependabot[bot] have not signed the CLA, adding error status to the pull request.
```

This is the PR which reproduces the issue:
https://github.com/karakun/encrypted-filechannel/pull/1

**Comment by sclassen** [comment]
OK, found the solution myself.
The correct name is `dependabot[bot]` without the @ sign

**Comment by ColinEberhardt** [comment]
Thanks for updating with the required fix @sclassen that's very useful.

**Comment by aspiers** [comment]
Please can this be documented? It took me ages to find this.
