### ISSUE TITLE
cla-bot not reacting on pull request

### ISSUE THREAD

**Issue by KiranNiranjan** [finos/cla-bot#199]
@maoo @ColinEberhardt This issue (https://github.com/finos/cla-bot/issues/23) is happening again https://github.com/symphonyoss/SymphonyElectron/pull/1294 cla-bot is not reacting to the pull request. 

Can you please take a look? Thank you

**Comment by maoo** [comment]
Hi @KiranNiranjan ! I'm closing this issue, as it's not related with the cla-bot code, but rather with FINOS operations; I'll drop a comment on the PR. TY!

**Comment by KiranNiranjan** [comment]
Thank you @maoo
