### ISSUE TITLE
Bot doesn't seem to recheck a branch if it's pushed to again

### ISSUE THREAD

**Issue by AndyMJones** [finos/cla-bot#3]
When a pull request is first put in, the bot signs it correctly. However, if someone amends a commit or rebases then pushes again, the bot doesn't resign the branch.

**Comment by ColinEberhardt** [comment]
@JohnEz thanks for pointing this out - can you reference a PR where this has become an issue? I guess the 'cla-signed' label is still present, but the status check needs to be performed again.

**Comment by AndyMJones** [comment]
It has happened on PR https://github.com/symphonyoss/ContainerJS/pull/117. And you are correct, the label is fine just the status needs approving.

**Comment by ColinEberhardt** [comment]
Should be fixed by https://github.com/ColinEberhardt/cla-bot/commit/39183ac62dbd9860414ea4db9a5549ffc529df92 will deploy this shortly
