### ISSUE TITLE
cla-bot adds multiple tags to repo after rebases

### ISSUE THREAD

**Issue by BenLambertNcl** [finos/cla-bot#36]
The bot adds the same tag multiple times if the pull request has been rebased (possibly pushed to as well). This could clutter up the pull request page if there were multiple rebases, although its not a big issue.

Example:
![image](https://user-images.githubusercontent.com/9324259/27726482-96962810-5d72-11e7-865c-1de4d980ebe7.png)

**Comment by BenLambertNcl** [comment]
Also note that the PR will need to be re-approved (see #3) but just doesn't need to reapply the tag

**Comment by ColinEberhardt** [comment]
See also https://github.com/symphonyoss/ContainerJS/pull/225 - it adds multiple comments
