### ISSUE TITLE
The configuration instructions for clabot-config on the website is wrong

### ISSUE THREAD

**Issue by zabil** [finos/cla-bot#62]
The instructions at https://colineberhardt.github.io/cla-bot/#configuration-options
says
> If you have multiple repositories within the same organization, or user account, that have the same contributors, you can create a single configuration by adding a project called clabot-config. For example, for my personal projects I could configure the bot via https://github.com/ColinEberhardt/cla-config/.clabot.

Should be

If you have multiple repositories within the same organization, or user account, that have the same contributors, you can create a single configuration by adding a project called clabot-config. For example, for my personal projects I could configure the bot via `https://github.com/ColinEberhardt/clabot-config/.clabot`.

Same here
> Note, if you do not want the list of contributors to be public, the cla-config project can be private.

should be

Note, if you do not want the list of contributors to be public, the **clabot**-config project can be private.

**Comment by ColinEberhardt** [comment]
Good spot - just updated the docs - does everything look right to you now?

**Comment by zabil** [comment]
Yes, all good! Closing it.

**Comment by ColinEberhardt** [comment]
Great - if you find any other issues, let me know.
