### ISSUE TITLE
cla-bot times out while trying to fetch the logs

### ISSUE THREAD

**Issue by zabil** [finos/cla-bot#64]
While trying test `cla-bot` on my repo it fails to check cla.
For e.g. https://github.com/zabil/listhandling/pull/8

The [details](https://colineberhardt.github.io/cla-bot/logs/?correlationKey=5386c1e0-7c14-11e7-9b1c-bfdf0361bffc) page fails with the XHR.
```
{"errorMessage":"2017-08-08T08:50:17.254Z 90fec5cf-7c16-11e7-962f-e18b63415a86 Task timed out after 15.00 seconds"}
```

Is there a way to check status of the cla-bot?

Thanks!

**Comment by ColinEberhardt** [comment]
OK, so I've just increased the time-out on the lambda function that fetches log data. I'm not sure this solution is terribly scaleable!

**Comment by zabil** [comment]
Thanks! I can see the logs now.
The log seems to say that i am returning the right json.

```
DEBUG: API Response https://sheltered-beach-60183.herokuapp.com/contributor?checkContributor=zabil expand
"{\"isContributor\":\"true\",\"username\":\"zabil\"}"'
INFO: The contributors @zabil have not signed the CLA, adding error status to the pull request
```
I notice the check saying  `@zabil`

Should json be.

```
{
  "isContributor": "true",
  "username": "@zabil"
}

```
?

**Comment by ColinEberhardt** [comment]
That looks like a bug! I'll investigate

**Comment by ColinEberhardt** [comment]
Have you switched to using a contributor array instead? I'm struggling to find the logs which exhibit this error!

**Comment by ColinEberhardt** [comment]
OK, I've found the underlying issue, the webhook response was not being parsed as JSON, so was always indicating a failure (i.e. regardless of the committer in the request, it was being translated as being a non-contributor).

I've just deployed a fix.

**Comment by zabil** [comment]
Works now!
Thanks for the awesome bot.
