### ISSUE TITLE
How to get user name in comment

### ISSUE THREAD

**Issue by BugDiver** [finos/cla-bot#69]
I would like to get the user name who has not signed the CLA in the comment. It becomes important when there a re multiple committers in same pull request. Mentioning the user who has not sign would be really good.
Is there any way to do that?

Sorry for raising an issue for a question but didn't find any chat medium.

**Comment by ColinEberhardt** [comment]
If you add the token {{usersWithoutCLA}} in the message it is expanded out to the list of GitHub users that have not signed the CLA.

No worries about opening up an issue. If you have any other questions, let me know

**Comment by ColinEberhardt** [comment]
Looks like Jekyll was messing up this part of the documentation: https://github.com/ColinEberhardt/cla-bot/commit/926d7a6bef3bbe4700b09ff93ff8bca125aba18c

**Comment by BugDiver** [comment]
I got it. So apparently it was an issue and I don't need to feel sorry 😄 😄
