### ISSUE TITLE
cla-bot duplicates GitHub user ids

### ISSUE THREAD

**Issue by pmonks** [finos/cla-bot#70]
When generating a message as a result of a CLA being missing, the cla-bot duplicates the same GitHub user id in some cases.

[Here's an example](https://github.com/symphonyoss/hubot-symphony/pull/60).

**Comment by ColinEberhardt** [comment]
Thanks for the bug report @pmonks - I'm going to take a look at fixing some of these issues shortly.

I've checked the logs, and it's great to see the bot has quite a few users :-)

**Comment by pmonks** [comment]
Oh yeah we’ve deployed it for all of our 60-odd repositories - it works great!  😉

**Comment by ColinEberhardt** [comment]
@pmonks Fixed :-)

@maoo there's a release with this, and another bug fix, here: https://github.com/ColinEberhardt/cla-bot/releases/tag/v1.0.1

**Comment by maoo** [comment]
Just redeployed cla-bot 1.0.1 on our Github App (`ssf-cla-bot`, only available for symphonyoss Github org) and tested on https://github.com/symphonyoss/clabot-test/pull/20 ; everything seems to work as expected. Thanks @ColinEberhardt !

**Comment by ColinEberhardt** [comment]
Cool, glad it went smoothly!
