### ISSUE TITLE
Question: is it possible for cla-bot to block merging of a PR?

### ISSUE THREAD

**Issue by pmonks** [finos/cla-bot#75]
Question: is it possible for cla-bot to **block** merging of a PR when a CLA isn't found for the submitter?

Currently cla-bot is advisory in nature - a project team member is able to overrule a cla-bot violation and merge a PR from a submitter who doesn't have a CLA, and there are cases where this should be prevented.

**Comment by ColinEberhardt** [comment]
Sure, you can actually achieve this using built-in GitHub functionality by setting up a protected branch. 

When a branch is protected you can specify that certain status checks are mandatory. Here's an example using ContainerJS:

<img width="1056" alt="screen shot 2017-10-10 at 22 19 54" src="https://user-images.githubusercontent.com/1098110/31411420-7fb08662-ae09-11e7-88f9-21f070d2f649.png">

(via https://github.com/symphonyoss/ContainerJS/settings/branches/master)

**Comment by pmonks** [comment]
While I'm well aware of protected branches, they aren't appropriate in this case since they require the cooperation of the project team (who are exactly the folks we're trying to prevent merging PRs from someone without a CLA).  Furthermore they impose a particular development workflow on the team that they may not otherwise wish to use.

Is there another mechanism that cannot, in any way, be circumvented by the project team (as protected branches can), and that (ideally) is orthogonal to the team's development workflow?

**Comment by ColinEberhardt** [comment]
Ah, I see! I am not aware of any mechanism other than protected branches. There is an API for this:

https://developer.github.com/v3/repos/branches/#update-branch-protection

However, this feels more like an administration / process thing. Users can only override this if you give them admin privileges on a repo. You could just give them read / write access which means they would be able to conduct their work as usual, but not make changes via the settings tab.

A bot doesn't have any extra functionality available to it.

**Comment by maoo** [comment]
Given the long time and the efforts we've put to look for a solution, I think we can safely answer that there is no way for the cla-bot to block PRs.

That being said, branch protection can be a way to achieve the same result (for specific branches); we're discussing automating branch protection configuration on https://github.com/finos/open-developer-platform/issues/120

**Comment by pmonks** [comment]
As [mentioned above](https://github.com/finos/cla-bot/issues/75#issuecomment-335616727), branch protection doesn't meet this requirement, and indeed it seems that GitHub doesn't provide any way to satisfy it.
