### ISSUE TITLE
cla-bot is case-sensitive, but GitHub is not

### ISSUE THREAD

**Issue by maoo** [finos/cla-bot#81]
Just realised that cla-bot is case-sensitive when comparing whitelisted GitHub IDs with PR contributors; code is on https://github.com/ColinEberhardt/cla-bot/blob/develop/cla-bot/contributionVerifier.js#L7

Wondering if we could/should change to:
```
const contributorArrayVerifier = contributors =>
  committers =>
    Promise.resolve(committers.filter(c => contributors.indexOf(c.toLowerCase()) === -1));
```

Another change must be applied when populating the list of committers, to force lowercase there too - https://github.com/ColinEberhardt/cla-bot/blob/develop/cla-bot/index.js#L127

```
const committers = sortUnique(commits.map(c => c.author.login.toLowerCase()));
```

I can easily send a PR, but wanted to gather some thoughts first.
Thanks! /cc @ColinEberhardt

**Comment by ColinEberhardt** [comment]
Ah, good point. I agree, this should be a case insensitive comparison. I'd be happy to receive a PR for that :-)

**Comment by maoo** [comment]
@ColinEberhardt - PR https://github.com/ColinEberhardt/cla-bot/pull/82 is ready for review!
