### ISSUE TITLE
license

### ISSUE THREAD

**Issue by glycerine** [finos/cla-bot#84]
This is very cool project. But oops, I don't see a LICENSE file on it. Kind of ironic, considering the purpose(!)

Anyhoo. Please put an MIT or public domain statement in the repo to confirm what the blog seems to suggest, that you intend to make this freely available to the public.

**Comment by ColinEberhardt** [comment]
Oops, good point! I've added it here: https://github.com/ColinEberhardt/cla-bot/blob/develop/LICENSE
