### ISSUE TITLE
cla-bot can summon itself, causing an infinite loop

### ISSUE THREAD

**Issue by dhaffner** [finos/cla-bot#87]
Thanks for your work! Just wanted to share a minor bug:

I added cla-bot to my org's repo and part of my `message` was:
>  ... say '@cla-bot check' to have the contributors list checked again ...

It seems like it would suffice to add a check at the same place we call `commentSummonsBot()` to ensure the comment author isn't the bot itself.

**Comment by ColinEberhardt** [comment]
Thanks, very well spotted! I've deployed a fix: https://github.com/ColinEberhardt/cla-bot/pull/88
